// COMIC ACTIONS
export const GET_COMICS = 'GET_COMICS';
export const ADD_COMICS = 'ADD_COMICS';
export const GET_COMIC_DETAIL = 'GET_COMIC_DETAIL';
export const GET_CHARACTERS_OF_COMIC = 'GET_CHARACTERS_OF_COMIC';
export const GET_CREATORS_OF_COMIC = 'GET_CREATORS_OF_COMIC';

// CHARACTERS ACTIONS
export const GET_CHARACTERS = 'GET_CHARACTERS';
export const ADD_CHARACTERS = 'ADD_CHARACTERS';
export const GET_CHARACTER_DETAIL = 'GET_CHARACTER_DETAIL';
export const GET_COMICS_OF_CHARACTER = 'GET_COMICS_OF_CHARACTER';
